spring.application.name=order-service


server.servlet.context-path=/orders
server.port=9020

spring.datasource.url=jdbc:postgresql://localhost:5432/orderDb
spring.datasource.username=postgres
spring.datasource.password=Ajay@9977
spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=always

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.sql.init.data-locations=classpath:data.sql

features.user-tracking-enabled=true

#eureka configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

#This is use for tracing in zipkin
management.tracing.sampling.probability=1.0