spring.application.name=RestAndMVC
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:file:/Users/Ajay Singh/OneDrive/Documents/DB
#spring.datasource.url=jdbc:h2:file:C:/Users/Syn A234/testdb
spring.datasource.username=ajay
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
