spring.application.name=springai
server.port=8081
spring.ai.ollama.base-url=http://localhost:11434
#spring.ai.ollama.chat.options.model=qwen3
#spring.ai.ollama.chat.options.model=qwen3:latest
spring.ai.ollama.chat.options.model=smollm2:360m

#spring.ai.openai.api-key=
#spring.ai..openai.chat.options.model=gpt-40-mini
#spring.ai..openai.chat.options.temperature=0.9

#spring.ai..openai.embedding.options.model=text-embedding-3-small

spring.ai.vectorstore.pgvector.initialize-schema=true

spring.datasource.url=jdbc:postgresql://localhost:5434/pgvector
spring.datasource.username=postgres
spring.datasource.password=Ajay@9977

spring.ai.chat.memory.repository.jdbc.initialize-schema=always

#spring.ai.chat.memory.repository.jdbc.initialize-scheme=always
#spring.ai.chat.memory.repository.jdbc.table-name=chat_memory