spring.application.name=aop

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/aop
spring.datasource.username=postgres
spring.datasource.password=Ajay@9977

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true